import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import {
  AlertCircle,
  Check,
  CheckSquare,
  ClipboardCopy,
  FileAudio,
  FileVideo,
  Gavel,
  Loader2,
  RotateCcw,
  Sparkles,
  Upload,
  Users,
  X,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { apiFetch, formatApiError } from "@/lib/api"
import { cn } from "@/lib/utils"

/* ── Types ─────────────────────────────────────────────────────────────── */

export type Priority = "high" | "medium" | "low"

export interface ActionItem {
  task: string
  owner: string
  due_date: string
  priority: Priority
}

export interface KeyDecision {
  decision: string
  rationale: string
  stakeholders: string[]
}

export interface MeetingMoM {
  title: string
  date_context: string
  participants: string[]
  executive_summary: string
  key_decisions: KeyDecision[]
  action_items: ActionItem[]
  topics_discussed: string[]
  next_steps: string[]
}

interface ApiSuccess {
  success: true
  filename: string
  mom: MeetingMoM
}

type Phase = "idle" | "processing" | "done" | "error"

const ACCEPTED =
  ".mp4,.mkv,.webm,.mov,.avi,.mp3,.wav,.m4a,.aac,.ogg,.flac,audio/*,video/*"

const LOADING_COPY = [
  "Uploading media securely…",
  "Extracting audio track…",
  "Feeding audio to Gemini…",
  "Listening for key decisions…",
  "Identifying action items…",
  "Synthesizing meeting insights…",
  "Formatting your minutes…",
  "Almost there — polishing the summary…",
]

const PRIORITY_STYLES: Record<Priority, string> = {
  high: "bg-red-500/15 text-red-400 border-red-500/30",
  medium: "bg-amber-500/15 text-amber-400 border-amber-500/30",
  low: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
}

/* ── Helpers ───────────────────────────────────────────────────────────── */

function isVideoFile(file: File): boolean {
  if (file.type.startsWith("video/")) return true
  return /\.(mp4|mkv|webm|mov|avi)$/i.test(file.name)
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function momToMarkdown(mom: MeetingMoM): string {
  const lines: string[] = []
  lines.push(`# ${mom.title}`)
  lines.push("")
  if (mom.date_context) lines.push(`**Date / context:** ${mom.date_context}`)
  if (mom.participants?.length) {
    lines.push(`**Participants:** ${mom.participants.join(", ")}`)
  }
  lines.push("")
  lines.push("## Executive Summary")
  lines.push("")
  lines.push(mom.executive_summary)
  lines.push("")

  if (mom.topics_discussed?.length) {
    lines.push("## Topics Discussed")
    lines.push("")
    for (const t of mom.topics_discussed) lines.push(`- ${t}`)
    lines.push("")
  }

  lines.push("## Key Decisions")
  lines.push("")
  if (!mom.key_decisions?.length) {
    lines.push("_No key decisions recorded._")
  } else {
    for (const d of mom.key_decisions) {
      lines.push(`### ${d.decision}`)
      lines.push("")
      lines.push(`**Rationale:** ${d.rationale}`)
      if (d.stakeholders?.length) {
        lines.push(`**Stakeholders:** ${d.stakeholders.join(", ")}`)
      }
      lines.push("")
    }
  }

  lines.push("## Action Items")
  lines.push("")
  if (!mom.action_items?.length) {
    lines.push("_No action items recorded._")
  } else {
    for (const a of mom.action_items) {
      lines.push(
        `- [ ] **${a.task}** — _${a.owner}_ · due ${a.due_date} · priority: ${a.priority}`
      )
    }
  }
  lines.push("")

  if (mom.next_steps?.length) {
    lines.push("## Next Steps")
    lines.push("")
    for (const s of mom.next_steps) lines.push(`- ${s}`)
    lines.push("")
  }

  lines.push("---")
  lines.push("_Generated by Meetingly · not stored on any server_")
  return lines.join("\n")
}

/* ── Subcomponents ─────────────────────────────────────────────────────── */

function LoadingOrb({ message }: { message: string }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 px-6 animate-fade-up">
      <div className="relative mb-10 h-28 w-28">
        <div className="absolute inset-0 rounded-full bg-brand/20 blur-2xl animate-orb-pulse" />
        <div className="absolute inset-2 rounded-full border border-brand/30 animate-orb-spin" />
        <div
          className="absolute inset-4 rounded-full border border-dashed border-violet-400/40 animate-orb-spin"
          style={{ animationDirection: "reverse", animationDuration: "12s" }}
        />
        <div className="absolute inset-0 flex items-center justify-center">
          <Sparkles className="h-8 w-8 text-brand animate-orb-pulse" />
        </div>
      </div>
      <p
        key={message}
        className="text-base font-medium text-foreground animate-fade-up text-center max-w-sm"
      >
        {message}
      </p>
      <p className="mt-2 text-sm text-muted-foreground text-center max-w-md">
        Gemini is analyzing the recording natively — this can take 30–90 seconds
        for longer meetings.
      </p>
      <div className="mt-6 flex items-center gap-2 text-xs text-muted-foreground">
        <Loader2 className="h-3.5 w-3.5 animate-spin" />
        Processing in memory · nothing is stored
      </div>
    </div>
  )
}

function DropZone({
  onFile,
  disabled,
}: {
  onFile: (file: File) => void
  disabled?: boolean
}) {
  const inputRef = useRef<HTMLInputElement>(null)
  const [dragOver, setDragOver] = useState(false)

  const handleFiles = useCallback(
    (list: FileList | null) => {
      if (!list?.length || disabled) return
      onFile(list[0])
    },
    [onFile, disabled]
  )

  return (
    <div
      role="button"
      tabIndex={0}
      onKeyDown={(e) => {
        if (e.key === "Enter" || e.key === " ") inputRef.current?.click()
      }}
      onDragOver={(e) => {
        e.preventDefault()
        if (!disabled) setDragOver(true)
      }}
      onDragLeave={() => setDragOver(false)}
      onDrop={(e) => {
        e.preventDefault()
        setDragOver(false)
        handleFiles(e.dataTransfer.files)
      }}
      onClick={() => !disabled && inputRef.current?.click()}
      className={cn(
        "group relative flex flex-col items-center justify-center rounded-xl border border-dashed px-6 py-16 transition-all cursor-pointer",
        dragOver
          ? "border-brand bg-brand/10 scale-[1.01]"
          : "border-border bg-card/40 hover:border-zinc-500 hover:bg-card/70",
        disabled && "opacity-50 pointer-events-none"
      )}
    >
      <input
        ref={inputRef}
        type="file"
        accept={ACCEPTED}
        className="hidden"
        onChange={(e) => handleFiles(e.target.files)}
      />
      <div className="mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-muted border border-border group-hover:border-brand/40 transition-colors">
        <Upload className="h-6 w-6 text-muted-foreground group-hover:text-brand transition-colors" />
      </div>
      <p className="text-base font-medium text-foreground">
        Drop a meeting recording
      </p>
      <p className="mt-1.5 text-sm text-muted-foreground text-center max-w-sm">
        Video (MP4, MKV, MOV) or audio (MP3, WAV, M4A) · max 100 MB
      </p>
      <div className="mt-6 flex items-center gap-3 text-xs text-muted-foreground">
        <span className="inline-flex items-center gap-1.5 rounded-full border border-border bg-muted px-2.5 py-1">
          <FileVideo className="h-3 w-3" /> Video
        </span>
        <span className="inline-flex items-center gap-1.5 rounded-full border border-border bg-muted px-2.5 py-1">
          <FileAudio className="h-3 w-3" /> Audio
        </span>
      </div>
    </div>
  )
}

function PriorityBadge({ priority }: { priority: Priority }) {
  return (
    <span
      className={cn(
        "inline-flex items-center rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide",
        PRIORITY_STYLES[priority] ?? PRIORITY_STYLES.medium
      )}
    >
      {priority}
    </span>
  )
}

function ResultsView({
  mom,
  filename,
  onReset,
}: {
  mom: MeetingMoM
  filename: string
  onReset: () => void
}) {
  const [copied, setCopied] = useState(false)
  const [checked, setChecked] = useState<Record<number, boolean>>({})

  const markdown = useMemo(() => momToMarkdown(mom), [mom])

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(markdown)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback for older browsers
      const ta = document.createElement("textarea")
      ta.value = markdown
      document.body.appendChild(ta)
      ta.select()
      document.execCommand("copy")
      document.body.removeChild(ta)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <div className="animate-fade-up space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div className="min-w-0 space-y-1">
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <Sparkles className="h-3.5 w-3.5 text-brand" />
            <span className="truncate">{filename}</span>
          </div>
          <h2 className="text-2xl font-semibold tracking-tight text-foreground">
            {mom.title}
          </h2>
          <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-muted-foreground">
            {mom.date_context && <span>{mom.date_context}</span>}
            {mom.participants?.length > 0 && (
              <span className="inline-flex items-center gap-1.5">
                <Users className="h-3.5 w-3.5" />
                {mom.participants.join(", ")}
              </span>
            )}
          </div>
        </div>
        <div className="flex shrink-0 items-center gap-2">
          <Button variant="outline" size="sm" onClick={onReset}>
            <RotateCcw className="h-3.5 w-3.5" />
            New file
          </Button>
          <Button variant="brand" size="sm" onClick={handleCopy}>
            {copied ? (
              <>
                <Check className="h-3.5 w-3.5" />
                Copied
              </>
            ) : (
              <>
                <ClipboardCopy className="h-3.5 w-3.5" />
                Copy Markdown
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Tabs */}
      <Tabs defaultValue="summary" className="w-full">
        <TabsList className="w-full sm:w-auto grid grid-cols-3 sm:inline-flex">
          <TabsTrigger value="summary" className="gap-1.5">
            <Sparkles className="h-3.5 w-3.5 hidden sm:block" />
            Executive Summary
          </TabsTrigger>
          <TabsTrigger value="decisions" className="gap-1.5">
            <Gavel className="h-3.5 w-3.5 hidden sm:block" />
            Key Decisions
            {mom.key_decisions?.length > 0 && (
              <span className="ml-1 rounded-full bg-muted-foreground/20 px-1.5 text-[10px]">
                {mom.key_decisions.length}
              </span>
            )}
          </TabsTrigger>
          <TabsTrigger value="actions" className="gap-1.5">
            <CheckSquare className="h-3.5 w-3.5 hidden sm:block" />
            Action Items
            {mom.action_items?.length > 0 && (
              <span className="ml-1 rounded-full bg-muted-foreground/20 px-1.5 text-[10px]">
                {mom.action_items.length}
              </span>
            )}
          </TabsTrigger>
        </TabsList>

        <TabsContent value="summary">
          <div className="rounded-xl border border-border bg-card p-6 space-y-6">
            <div className="prose prose-invert max-w-none">
              {mom.executive_summary.split("\n").filter(Boolean).map((p, i) => (
                <p
                  key={i}
                  className="text-[15px] leading-relaxed text-zinc-300 mb-4 last:mb-0"
                >
                  {p}
                </p>
              ))}
            </div>

            {mom.topics_discussed?.length > 0 && (
              <div>
                <h3 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">
                  Topics discussed
                </h3>
                <ul className="flex flex-wrap gap-2">
                  {mom.topics_discussed.map((topic) => (
                    <li
                      key={topic}
                      className="rounded-md border border-border bg-muted px-2.5 py-1 text-sm text-zinc-300"
                    >
                      {topic}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {mom.next_steps?.length > 0 && (
              <div>
                <h3 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">
                  Next steps
                </h3>
                <ul className="space-y-2">
                  {mom.next_steps.map((step, i) => (
                    <li
                      key={i}
                      className="flex gap-2 text-sm text-zinc-300 leading-relaxed"
                    >
                      <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-brand" />
                      {step}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </TabsContent>

        <TabsContent value="decisions">
          <div className="rounded-xl border border-border bg-card p-6">
            {!mom.key_decisions?.length ? (
              <p className="text-sm text-muted-foreground text-center py-8">
                No key decisions were identified in this recording.
              </p>
            ) : (
              <ul className="space-y-4">
                {mom.key_decisions.map((d, i) => (
                  <li
                    key={i}
                    className="rounded-lg border border-border bg-muted/40 p-4 space-y-2"
                  >
                    <div className="flex items-start gap-3">
                      <div className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-brand/15 text-brand text-xs font-bold">
                        {i + 1}
                      </div>
                      <div className="min-w-0 space-y-1.5">
                        <p className="font-medium text-foreground leading-snug">
                          {d.decision}
                        </p>
                        <p className="text-sm text-muted-foreground leading-relaxed">
                          <span className="text-zinc-400">Rationale: </span>
                          {d.rationale}
                        </p>
                        {d.stakeholders?.length > 0 && (
                          <p className="text-xs text-muted-foreground">
                            Stakeholders: {d.stakeholders.join(", ")}
                          </p>
                        )}
                      </div>
                    </div>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </TabsContent>

        <TabsContent value="actions">
          <div className="rounded-xl border border-border bg-card p-6">
            {!mom.action_items?.length ? (
              <p className="text-sm text-muted-foreground text-center py-8">
                No action items were identified in this recording.
              </p>
            ) : (
              <ul className="space-y-3">
                {mom.action_items.map((item, i) => {
                  const isDone = !!checked[i]
                  return (
                    <li
                      key={i}
                      className={cn(
                        "flex items-start gap-3 rounded-lg border border-border bg-muted/40 p-4 transition-opacity",
                        isDone && "opacity-55"
                      )}
                    >
                      <Checkbox
                        id={`action-${i}`}
                        checked={isDone}
                        onCheckedChange={(v) =>
                          setChecked((prev) => ({ ...prev, [i]: v === true }))
                        }
                        className="mt-0.5"
                      />
                      <label
                        htmlFor={`action-${i}`}
                        className="min-w-0 flex-1 cursor-pointer space-y-1.5"
                      >
                        <p
                          className={cn(
                            "font-medium text-foreground leading-snug",
                            isDone && "line-through text-muted-foreground"
                          )}
                        >
                          {item.task}
                        </p>
                        <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                          <span className="rounded border border-border bg-background px-1.5 py-0.5">
                            {item.owner}
                          </span>
                          <span>Due: {item.due_date}</span>
                          <PriorityBadge priority={item.priority} />
                        </div>
                      </label>
                    </li>
                  )
                })}
              </ul>
            )}
          </div>
        </TabsContent>
      </Tabs>
    </div>
  )
}

/* ── Main workspace ────────────────────────────────────────────────────── */

export function MoMWorkspace() {
  const [phase, setPhase] = useState<Phase>("idle")
  const [file, setFile] = useState<File | null>(null)
  const [mom, setMom] = useState<MeetingMoM | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [copyIndex, setCopyIndex] = useState(0)
  const abortRef = useRef<AbortController | null>(null)

  // Cycle loading messages while processing
  useEffect(() => {
    if (phase !== "processing") return
    setCopyIndex(0)
    const id = window.setInterval(() => {
      setCopyIndex((i) => (i + 1) % LOADING_COPY.length)
    }, 3200)
    return () => window.clearInterval(id)
  }, [phase])

  const reset = useCallback(() => {
    abortRef.current?.abort()
    abortRef.current = null
    setPhase("idle")
    setFile(null)
    setMom(null)
    setError(null)
  }, [])

  const processFile = useCallback(async (selected: File) => {
    setFile(selected)
    setPhase("processing")
    setError(null)
    setMom(null)

    const controller = new AbortController()
    abortRef.current = controller

    const form = new FormData()
    form.append("file", selected)

    try {
      const res = await apiFetch("/api/generate-mom", {
        method: "POST",
        body: form,
        signal: controller.signal,
      })

      let payload: unknown
      try {
        payload = await res.json()
      } catch {
        throw new Error(
          res.ok
            ? "Invalid response from server"
            : `Request failed (${res.status})`
        )
      }

      if (!res.ok) {
        if (res.status === 401) {
          throw new Error(
            "Your session expired or you are not signed in. Please sign in again."
          )
        }
        throw new Error(
          formatApiError(payload, `Request failed (${res.status})`)
        )
      }

      const success = payload as ApiSuccess
      if (!success?.mom) {
        throw new Error("Server returned an unexpected response.")
      }
      setMom(success.mom)
      setPhase("done")
    } catch (err) {
      if (err instanceof DOMException && err.name === "AbortError") return
      const message =
        err instanceof Error ? err.message : "Something went wrong"
      setError(message)
      setPhase("error")
    } finally {
      abortRef.current = null
    }
  }, [])

  return (
    <div className="w-full max-w-3xl mx-auto">
      {phase === "idle" && (
        <div className="space-y-4 animate-fade-up">
          <DropZone onFile={processFile} />
          <p className="text-center text-xs text-muted-foreground">
            Files are processed in memory and discarded immediately. Nothing is
            written to a database or long-term storage.
          </p>
        </div>
      )}

      {phase === "processing" && file && (
        <div className="rounded-xl border border-border bg-card overflow-hidden">
          <div className="flex items-center justify-between border-b border-border px-4 py-3">
            <div className="flex items-center gap-2 min-w-0 text-sm">
              {isVideoFile(file) ? (
                <FileVideo className="h-4 w-4 shrink-0 text-brand" />
              ) : (
                <FileAudio className="h-4 w-4 shrink-0 text-brand" />
              )}
              <span className="truncate font-medium">{file.name}</span>
              <span className="shrink-0 text-muted-foreground">
                {formatBytes(file.size)}
              </span>
            </div>
            <Button
              variant="ghost"
              size="icon"
              className="h-8 w-8 shrink-0"
              onClick={reset}
              aria-label="Cancel"
            >
              <X className="h-4 w-4" />
            </Button>
          </div>
          <LoadingOrb message={LOADING_COPY[copyIndex]} />
        </div>
      )}

      {phase === "error" && (
        <div className="animate-fade-up rounded-xl border border-destructive/40 bg-destructive/5 p-6 space-y-4">
          <div className="flex items-start gap-3">
            <AlertCircle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />
            <div className="space-y-1 min-w-0">
              <p className="font-medium text-foreground">
                Failed to generate minutes
              </p>
              <p className="text-sm text-muted-foreground break-words">
                {error}
              </p>
              {file && (
                <p className="text-xs text-muted-foreground pt-1">
                  File: {file.name} ({formatBytes(file.size)})
                </p>
              )}
            </div>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={reset}>
              <RotateCcw className="h-3.5 w-3.5" />
              Try another file
            </Button>
            {file && (
              <Button
                variant="brand"
                size="sm"
                onClick={() => processFile(file)}
              >
                Retry
              </Button>
            )}
          </div>
        </div>
      )}

      {phase === "done" && mom && file && (
        <ResultsView mom={mom} filename={file.name} onReset={reset} />
      )}
    </div>
  )
}

export default MoMWorkspace
